Repository jenkinsci/google-chat-notification-plugin, pull requests merged in 2023-04, with the labels that each got.

#37 new structs version
  pom.xml
Labels: dependencies

#38 Don't use deprecated org.apache.commons.httpclient
  src/main/java/io/cnaik/service/CommonUtil.java
Labels: bug

#41 Plugin improvements (from the "Improve a Plugin Tutorial")
  .github/dependabot.yml
  .mvn/extensions.xml
  .mvn/maven.config
  README.md
  pom.xml
  src/main/java/io/cnaik/GoogleChatNotification.java
  src/main/java/io/cnaik/model/google/Cards.java
  src/main/java/io/cnaik/model/google/Header.java
  src/main/java/io/cnaik/model/google/Response.java
  src/main/java/io/cnaik/model/google/Sections.java
  src/main/java/io/cnaik/model/google/TextParagraph.java
  src/main/java/io/cnaik/model/google/Widgets.java
  src/main/java/io/cnaik/service/CommonUtil.java
  src/main/java/io/cnaik/service/ResponseMessageUtil.java
Labels: developer

#42 Update README
  README.md
  docs/details.png
Labels: documentation
